


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 570, 672))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_11.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_11.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_11.addWidget(self.pushButton_21)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_12.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_12.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_12.addWidget(self.pushButton_24)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_8.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_8.addWidget(self.pushButton_15)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_9.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_9.addWidget(self.pushButton_18)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_14.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_14.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_14.addWidget(self.pushButton_27)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_28 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_15.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_15.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_15.addWidget(self.pushButton_30)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_28.addWidget(self.label_10)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.pushButton_55 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_55.setObjectName("pushButton_55")
        self.horizontalLayout_29.addWidget(self.pushButton_55)
        self.pushButton_56 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_56.setObjectName("pushButton_56")
        self.horizontalLayout_29.addWidget(self.pushButton_56)
        self.pushButton_57 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_57.setObjectName("pushButton_57")
        self.horizontalLayout_29.addWidget(self.pushButton_57)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_29)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem5)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_58 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_58.setObjectName("pushButton_58")
        self.horizontalLayout_30.addWidget(self.pushButton_58)
        self.pushButton_59 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_59.setObjectName("pushButton_59")
        self.horizontalLayout_30.addWidget(self.pushButton_59)
        self.pushButton_60 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_60.setObjectName("pushButton_60")
        self.horizontalLayout_30.addWidget(self.pushButton_60)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_19.addWidget(self.label_7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_37 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_20.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_20.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_20.addWidget(self.pushButton_39)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_40 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_21.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_21.addWidget(self.pushButton_41)
        self.pushButton_42 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_21.addWidget(self.pushButton_42)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_22.addWidget(self.label_8)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_43 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_23.addWidget(self.pushButton_43)
        self.pushButton_44 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_23.addWidget(self.pushButton_44)
        self.pushButton_45 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_23.addWidget(self.pushButton_45)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_46 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_24.addWidget(self.pushButton_46)
        self.pushButton_47 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_24.addWidget(self.pushButton_47)
        self.pushButton_48 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout_24.addWidget(self.pushButton_48)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_31 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_17.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_17.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_17.addWidget(self.pushButton_33)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_34 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_18.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_18.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_18.addWidget(self.pushButton_36)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_25.addWidget(self.label_9)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pushButton_49 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_49.setObjectName("pushButton_49")
        self.horizontalLayout_26.addWidget(self.pushButton_49)
        self.pushButton_50 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout_26.addWidget(self.pushButton_50)
        self.pushButton_51 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_51.setObjectName("pushButton_51")
        self.horizontalLayout_26.addWidget(self.pushButton_51)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem9)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.pushButton_52 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_52.setObjectName("pushButton_52")
        self.horizontalLayout_27.addWidget(self.pushButton_52)
        self.pushButton_53 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_53.setObjectName("pushButton_53")
        self.horizontalLayout_27.addWidget(self.pushButton_53)
        self.pushButton_54 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_54.setObjectName("pushButton_54")
        self.horizontalLayout_27.addWidget(self.pushButton_54)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_43.addWidget(self.label_15)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.pushButton_85 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_85.setObjectName("pushButton_85")
        self.horizontalLayout_44.addWidget(self.pushButton_85)
        self.pushButton_86 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_86.setObjectName("pushButton_86")
        self.horizontalLayout_44.addWidget(self.pushButton_86)
        self.pushButton_87 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_87.setObjectName("pushButton_87")
        self.horizontalLayout_44.addWidget(self.pushButton_87)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_44)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem10)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.pushButton_88 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_88.setObjectName("pushButton_88")
        self.horizontalLayout_45.addWidget(self.pushButton_88)
        self.pushButton_89 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_89.setObjectName("pushButton_89")
        self.horizontalLayout_45.addWidget(self.pushButton_89)
        self.pushButton_90 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_90.setObjectName("pushButton_90")
        self.horizontalLayout_45.addWidget(self.pushButton_90)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_45)
        self.verticalLayout_2.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_34.addWidget(self.label_12)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.pushButton_67 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_67.setObjectName("pushButton_67")
        self.horizontalLayout_35.addWidget(self.pushButton_67)
        self.pushButton_68 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_68.setObjectName("pushButton_68")
        self.horizontalLayout_35.addWidget(self.pushButton_68)
        self.pushButton_69 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_69.setObjectName("pushButton_69")
        self.horizontalLayout_35.addWidget(self.pushButton_69)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_35)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem11)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.pushButton_70 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_70.setObjectName("pushButton_70")
        self.horizontalLayout_36.addWidget(self.pushButton_70)
        self.pushButton_71 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_71.setObjectName("pushButton_71")
        self.horizontalLayout_36.addWidget(self.pushButton_71)
        self.pushButton_72 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_72.setObjectName("pushButton_72")
        self.horizontalLayout_36.addWidget(self.pushButton_72)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_37.addWidget(self.label_13)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.pushButton_73 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_73.setObjectName("pushButton_73")
        self.horizontalLayout_38.addWidget(self.pushButton_73)
        self.pushButton_74 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_74.setObjectName("pushButton_74")
        self.horizontalLayout_38.addWidget(self.pushButton_74)
        self.pushButton_75 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_75.setObjectName("pushButton_75")
        self.horizontalLayout_38.addWidget(self.pushButton_75)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_38)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem12)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.pushButton_76 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_76.setObjectName("pushButton_76")
        self.horizontalLayout_39.addWidget(self.pushButton_76)
        self.pushButton_77 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_77.setObjectName("pushButton_77")
        self.horizontalLayout_39.addWidget(self.pushButton_77)
        self.pushButton_78 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_78.setObjectName("pushButton_78")
        self.horizontalLayout_39.addWidget(self.pushButton_78)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_39)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_31.addWidget(self.label_11)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_61 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_61.setObjectName("pushButton_61")
        self.horizontalLayout_32.addWidget(self.pushButton_61)
        self.pushButton_62 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_62.setObjectName("pushButton_62")
        self.horizontalLayout_32.addWidget(self.pushButton_62)
        self.pushButton_63 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_63.setObjectName("pushButton_63")
        self.horizontalLayout_32.addWidget(self.pushButton_63)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_32)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem13)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_64 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_64.setObjectName("pushButton_64")
        self.horizontalLayout_33.addWidget(self.pushButton_64)
        self.pushButton_65 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_65.setObjectName("pushButton_65")
        self.horizontalLayout_33.addWidget(self.pushButton_65)
        self.pushButton_66 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_66.setObjectName("pushButton_66")
        self.horizontalLayout_33.addWidget(self.pushButton_66)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_33)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_40.addWidget(self.label_14)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.pushButton_79 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_79.setObjectName("pushButton_79")
        self.horizontalLayout_41.addWidget(self.pushButton_79)
        self.pushButton_80 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_80.setObjectName("pushButton_80")
        self.horizontalLayout_41.addWidget(self.pushButton_80)
        self.pushButton_81 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_81.setObjectName("pushButton_81")
        self.horizontalLayout_41.addWidget(self.pushButton_81)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_41)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem14)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.pushButton_82 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_82.setObjectName("pushButton_82")
        self.horizontalLayout_42.addWidget(self.pushButton_82)
        self.pushButton_83 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_83.setObjectName("pushButton_83")
        self.horizontalLayout_42.addWidget(self.pushButton_83)
        self.pushButton_84 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_84.setObjectName("pushButton_84")
        self.horizontalLayout_42.addWidget(self.pushButton_84)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_42)
        self.verticalLayout_2.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_58.addWidget(self.label_20)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.pushButton_115 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_115.setObjectName("pushButton_115")
        self.horizontalLayout_59.addWidget(self.pushButton_115)
        self.pushButton_116 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_116.setObjectName("pushButton_116")
        self.horizontalLayout_59.addWidget(self.pushButton_116)
        self.pushButton_117 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_117.setObjectName("pushButton_117")
        self.horizontalLayout_59.addWidget(self.pushButton_117)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_59)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem15)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.pushButton_118 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_118.setObjectName("pushButton_118")
        self.horizontalLayout_60.addWidget(self.pushButton_118)
        self.pushButton_119 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_119.setObjectName("pushButton_119")
        self.horizontalLayout_60.addWidget(self.pushButton_119)
        self.pushButton_120 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_120.setObjectName("pushButton_120")
        self.horizontalLayout_60.addWidget(self.pushButton_120)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_60)
        self.verticalLayout_2.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_49.addWidget(self.label_17)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.pushButton_97 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_97.setObjectName("pushButton_97")
        self.horizontalLayout_50.addWidget(self.pushButton_97)
        self.pushButton_98 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_98.setObjectName("pushButton_98")
        self.horizontalLayout_50.addWidget(self.pushButton_98)
        self.pushButton_99 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_99.setObjectName("pushButton_99")
        self.horizontalLayout_50.addWidget(self.pushButton_99)
        self.horizontalLayout_49.addLayout(self.horizontalLayout_50)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem16)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.pushButton_100 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_100.setObjectName("pushButton_100")
        self.horizontalLayout_51.addWidget(self.pushButton_100)
        self.pushButton_101 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_101.setObjectName("pushButton_101")
        self.horizontalLayout_51.addWidget(self.pushButton_101)
        self.pushButton_102 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_102.setObjectName("pushButton_102")
        self.horizontalLayout_51.addWidget(self.pushButton_102)
        self.horizontalLayout_49.addLayout(self.horizontalLayout_51)
        self.verticalLayout_2.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_52.addWidget(self.label_18)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.pushButton_103 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_103.setObjectName("pushButton_103")
        self.horizontalLayout_53.addWidget(self.pushButton_103)
        self.pushButton_104 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_104.setObjectName("pushButton_104")
        self.horizontalLayout_53.addWidget(self.pushButton_104)
        self.pushButton_105 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_105.setObjectName("pushButton_105")
        self.horizontalLayout_53.addWidget(self.pushButton_105)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_53)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem17)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.pushButton_106 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_106.setObjectName("pushButton_106")
        self.horizontalLayout_54.addWidget(self.pushButton_106)
        self.pushButton_107 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_107.setObjectName("pushButton_107")
        self.horizontalLayout_54.addWidget(self.pushButton_107)
        self.pushButton_108 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_108.setObjectName("pushButton_108")
        self.horizontalLayout_54.addWidget(self.pushButton_108)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_54)
        self.verticalLayout_2.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_46.addWidget(self.label_16)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.pushButton_91 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_91.setObjectName("pushButton_91")
        self.horizontalLayout_47.addWidget(self.pushButton_91)
        self.pushButton_92 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_92.setObjectName("pushButton_92")
        self.horizontalLayout_47.addWidget(self.pushButton_92)
        self.pushButton_93 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_93.setObjectName("pushButton_93")
        self.horizontalLayout_47.addWidget(self.pushButton_93)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_47)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem18)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.pushButton_94 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_94.setObjectName("pushButton_94")
        self.horizontalLayout_48.addWidget(self.pushButton_94)
        self.pushButton_95 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_95.setObjectName("pushButton_95")
        self.horizontalLayout_48.addWidget(self.pushButton_95)
        self.pushButton_96 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_96.setObjectName("pushButton_96")
        self.horizontalLayout_48.addWidget(self.pushButton_96)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_48)
        self.verticalLayout_2.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_55.addWidget(self.label_19)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.pushButton_109 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_109.setObjectName("pushButton_109")
        self.horizontalLayout_56.addWidget(self.pushButton_109)
        self.pushButton_110 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_110.setObjectName("pushButton_110")
        self.horizontalLayout_56.addWidget(self.pushButton_110)
        self.pushButton_111 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_111.setObjectName("pushButton_111")
        self.horizontalLayout_56.addWidget(self.pushButton_111)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_56)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem19)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.pushButton_112 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_112.setObjectName("pushButton_112")
        self.horizontalLayout_57.addWidget(self.pushButton_112)
        self.pushButton_113 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_113.setObjectName("pushButton_113")
        self.horizontalLayout_57.addWidget(self.pushButton_113)
        self.pushButton_114 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_114.setObjectName("pushButton_114")
        self.horizontalLayout_57.addWidget(self.pushButton_114)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_57)
        self.verticalLayout_2.addLayout(self.horizontalLayout_55)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuSettings.addAction(self.actionQuit)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_21.setText(_translate("MainWindow", "Choose your seats"))
        self.label.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "A"))
        self.pushButton_2.setText(_translate("MainWindow", "B"))
        self.pushButton_3.setText(_translate("MainWindow", "C"))
        self.pushButton_4.setText(_translate("MainWindow", "D"))
        self.pushButton_5.setText(_translate("MainWindow", "E"))
        self.pushButton_6.setText(_translate("MainWindow", "F"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.pushButton_7.setText(_translate("MainWindow", "A"))
        self.pushButton_8.setText(_translate("MainWindow", "B"))
        self.pushButton_9.setText(_translate("MainWindow", "C"))
        self.pushButton_10.setText(_translate("MainWindow", "D"))
        self.pushButton_11.setText(_translate("MainWindow", "E"))
        self.pushButton_12.setText(_translate("MainWindow", "F"))
        self.label_4.setText(_translate("MainWindow", "3"))
        self.pushButton_19.setText(_translate("MainWindow", "A"))
        self.pushButton_20.setText(_translate("MainWindow", "B"))
        self.pushButton_21.setText(_translate("MainWindow", "C"))
        self.pushButton_22.setText(_translate("MainWindow", "D"))
        self.pushButton_23.setText(_translate("MainWindow", "E"))
        self.pushButton_24.setText(_translate("MainWindow", "F"))
        self.label_3.setText(_translate("MainWindow", "4"))
        self.pushButton_13.setText(_translate("MainWindow", "A"))
        self.pushButton_14.setText(_translate("MainWindow", "B"))
        self.pushButton_15.setText(_translate("MainWindow", "C"))
        self.pushButton_16.setText(_translate("MainWindow", "D"))
        self.pushButton_17.setText(_translate("MainWindow", "E"))
        self.pushButton_18.setText(_translate("MainWindow", "F"))
        self.label_5.setText(_translate("MainWindow", "5"))
        self.pushButton_25.setText(_translate("MainWindow", "A"))
        self.pushButton_26.setText(_translate("MainWindow", "B"))
        self.pushButton_27.setText(_translate("MainWindow", "C"))
        self.pushButton_28.setText(_translate("MainWindow", "D"))
        self.pushButton_29.setText(_translate("MainWindow", "E"))
        self.pushButton_30.setText(_translate("MainWindow", "F"))
        self.label_10.setText(_translate("MainWindow", "6"))
        self.pushButton_55.setText(_translate("MainWindow", "A"))
        self.pushButton_56.setText(_translate("MainWindow", "B"))
        self.pushButton_57.setText(_translate("MainWindow", "C"))
        self.pushButton_58.setText(_translate("MainWindow", "D"))
        self.pushButton_59.setText(_translate("MainWindow", "E"))
        self.pushButton_60.setText(_translate("MainWindow", "F"))
        self.label_7.setText(_translate("MainWindow", "7"))
        self.pushButton_37.setText(_translate("MainWindow", "A"))
        self.pushButton_38.setText(_translate("MainWindow", "B"))
        self.pushButton_39.setText(_translate("MainWindow", "C"))
        self.pushButton_40.setText(_translate("MainWindow", "D"))
        self.pushButton_41.setText(_translate("MainWindow", "E"))
        self.pushButton_42.setText(_translate("MainWindow", "F"))
        self.label_8.setText(_translate("MainWindow", "8"))
        self.pushButton_43.setText(_translate("MainWindow", "A"))
        self.pushButton_44.setText(_translate("MainWindow", "B"))
        self.pushButton_45.setText(_translate("MainWindow", "C"))
        self.pushButton_46.setText(_translate("MainWindow", "D"))
        self.pushButton_47.setText(_translate("MainWindow", "E"))
        self.pushButton_48.setText(_translate("MainWindow", "F"))
        self.label_6.setText(_translate("MainWindow", "9"))
        self.pushButton_31.setText(_translate("MainWindow", "A"))
        self.pushButton_32.setText(_translate("MainWindow", "B"))
        self.pushButton_33.setText(_translate("MainWindow", "C"))
        self.pushButton_34.setText(_translate("MainWindow", "D"))
        self.pushButton_35.setText(_translate("MainWindow", "E"))
        self.pushButton_36.setText(_translate("MainWindow", "F"))
        self.label_9.setText(_translate("MainWindow", "10"))
        self.pushButton_49.setText(_translate("MainWindow", "A"))
        self.pushButton_50.setText(_translate("MainWindow", "B"))
        self.pushButton_51.setText(_translate("MainWindow", "C"))
        self.pushButton_52.setText(_translate("MainWindow", "D"))
        self.pushButton_53.setText(_translate("MainWindow", "E"))
        self.pushButton_54.setText(_translate("MainWindow", "F"))
        self.label_15.setText(_translate("MainWindow", "11"))
        self.pushButton_85.setText(_translate("MainWindow", "A"))
        self.pushButton_86.setText(_translate("MainWindow", "B"))
        self.pushButton_87.setText(_translate("MainWindow", "C"))
        self.pushButton_88.setText(_translate("MainWindow", "D"))
        self.pushButton_89.setText(_translate("MainWindow", "E"))
        self.pushButton_90.setText(_translate("MainWindow", "F"))
        self.label_12.setText(_translate("MainWindow", "12"))
        self.pushButton_67.setText(_translate("MainWindow", "A"))
        self.pushButton_68.setText(_translate("MainWindow", "B"))
        self.pushButton_69.setText(_translate("MainWindow", "C"))
        self.pushButton_70.setText(_translate("MainWindow", "D"))
        self.pushButton_71.setText(_translate("MainWindow", "E"))
        self.pushButton_72.setText(_translate("MainWindow", "F"))
        self.label_13.setText(_translate("MainWindow", "13"))
        self.pushButton_73.setText(_translate("MainWindow", "A"))
        self.pushButton_74.setText(_translate("MainWindow", "B"))
        self.pushButton_75.setText(_translate("MainWindow", "C"))
        self.pushButton_76.setText(_translate("MainWindow", "D"))
        self.pushButton_77.setText(_translate("MainWindow", "E"))
        self.pushButton_78.setText(_translate("MainWindow", "F"))
        self.label_11.setText(_translate("MainWindow", "14"))
        self.pushButton_61.setText(_translate("MainWindow", "A"))
        self.pushButton_62.setText(_translate("MainWindow", "B"))
        self.pushButton_63.setText(_translate("MainWindow", "C"))
        self.pushButton_64.setText(_translate("MainWindow", "D"))
        self.pushButton_65.setText(_translate("MainWindow", "E"))
        self.pushButton_66.setText(_translate("MainWindow", "F"))
        self.label_14.setText(_translate("MainWindow", "15"))
        self.pushButton_79.setText(_translate("MainWindow", "A"))
        self.pushButton_80.setText(_translate("MainWindow", "B"))
        self.pushButton_81.setText(_translate("MainWindow", "C"))
        self.pushButton_82.setText(_translate("MainWindow", "D"))
        self.pushButton_83.setText(_translate("MainWindow", "E"))
        self.pushButton_84.setText(_translate("MainWindow", "F"))
        self.label_20.setText(_translate("MainWindow", "16"))
        self.pushButton_115.setText(_translate("MainWindow", "A"))
        self.pushButton_116.setText(_translate("MainWindow", "B"))
        self.pushButton_117.setText(_translate("MainWindow", "C"))
        self.pushButton_118.setText(_translate("MainWindow", "D"))
        self.pushButton_119.setText(_translate("MainWindow", "E"))
        self.pushButton_120.setText(_translate("MainWindow", "F"))
        self.label_17.setText(_translate("MainWindow", "17"))
        self.pushButton_97.setText(_translate("MainWindow", "A"))
        self.pushButton_98.setText(_translate("MainWindow", "B"))
        self.pushButton_99.setText(_translate("MainWindow", "C"))
        self.pushButton_100.setText(_translate("MainWindow", "D"))
        self.pushButton_101.setText(_translate("MainWindow", "E"))
        self.pushButton_102.setText(_translate("MainWindow", "F"))
        self.label_18.setText(_translate("MainWindow", "18"))
        self.pushButton_103.setText(_translate("MainWindow", "A"))
        self.pushButton_104.setText(_translate("MainWindow", "B"))
        self.pushButton_105.setText(_translate("MainWindow", "C"))
        self.pushButton_106.setText(_translate("MainWindow", "D"))
        self.pushButton_107.setText(_translate("MainWindow", "E"))
        self.pushButton_108.setText(_translate("MainWindow", "F"))
        self.label_16.setText(_translate("MainWindow", "19"))
        self.pushButton_91.setText(_translate("MainWindow", "A"))
        self.pushButton_92.setText(_translate("MainWindow", "B"))
        self.pushButton_93.setText(_translate("MainWindow", "C"))
        self.pushButton_94.setText(_translate("MainWindow", "D"))
        self.pushButton_95.setText(_translate("MainWindow", "E"))
        self.pushButton_96.setText(_translate("MainWindow", "F"))
        self.label_19.setText(_translate("MainWindow", "20"))
        self.pushButton_109.setText(_translate("MainWindow", "A"))
        self.pushButton_110.setText(_translate("MainWindow", "B"))
        self.pushButton_111.setText(_translate("MainWindow", "C"))
        self.pushButton_112.setText(_translate("MainWindow", "D"))
        self.pushButton_113.setText(_translate("MainWindow", "E"))
        self.pushButton_114.setText(_translate("MainWindow", "F"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
